service: notes-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: rune
  region: eu-north-1
  iam:
    role: arn:aws:iam::175775313215:role/lectures-cloud


plugins:
  - serverless-webpack

package:
  individually: true  

functions:
  postNotes:
    handler: functions/postNotes/index.handler
    events:
      - httpApi:
          path: '/notes'
          method: POST
  getNotes:
    handler: functions/getNotes/index.handler
    events:
      - httpApi:
          path: "/notes"
          method: GET                
  updateNotes:
    handler: functions/updateNotes/index.handler
    events:
      - httpApi:
          path: '/notes'
          method: PUT
  deleteNotes:
    handler: functions/deleteNotes/index.handler
    events:
      - httpApi:
          path: '/notes'
          method: DELETE
  signUp:
     handler: functions/signUp/index.handler
     events: 
      - httpApi:
          path: '/user/signup'
          method: POST
  logIn:
    handler: functions/logIn/index.handler
    events:
      - httpApi:
          path: '/user/login'
          method: POST        


resources:  
  Resources:
    notesDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notes-db
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    accountsDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notes-accounts
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST    


           
